#!/bin/bash -e

# Assuming ~/inet ~/nesting and are existing and built INET and NeSTiNg repositories,
# and ~/omnetpp-summit-hackathon-2018 is this repository


DIR=`dirname $0`

INET_DIR=$DIR/../inet
NESTING_DIR=$DIR/../nesting

DBG=_dbg # change to empty string to run release version

XML_FILE=$1

NED_FILE=${1/".xml"/".ned"}

# echo $XML_FILE $NED_FILE

shift

python3 $DIR/yang-to-opp/yang-to-opp.py $XML_FILE $NED_FILE

NETWORK=$(egrep 'network ' $NED_FILE | cut -d ' '  -f 2)

# This "empty" file still has to be there, even though the generated .ned is self-contained
echo "[General]" > omnetpp.ini

echo "opp_run$DBG -n .:$INET_DIR/src:$NESTING_DIR/src -l $INET_DIR/src/libINET$DBG.so -l $NESTING_DIR/src/libnesting$DBG.so --image-path=$INET_DIR/images --network=$NETWORK "$@""

opp_run$DBG -n .:$INET_DIR/src:$NESTING_DIR/src -l $INET_DIR/src/libINET$DBG.so -l $NESTING_DIR/src/libnesting$DBG.so --image-path=$INET_DIR/images --network=$NETWORK "$@"

# echo $NETWORK
